version: "3"

services:
  firstapp:
    image: jgerges/updatedapp:latest
    container_name: firstapp
    ports:
    - 5000:5000

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    command: --prefix=/jenkins
    ports:
    - 8080:8080
    volumes:
    - jenkins_data:/var/jenkins_home
       
  sonar:
    image: ${SONAR_IMAGE}
    container_name: sonarqube
    command: -Dsonar.web.context=/sonar
    environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    ports:
    - 9000:9000
    volumes:
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_logs:/opt/sonarqube/logs
  
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    environment:
    - NEXUS_CONTEXT=nexus
    ports:
    - 8081:8081
    volumes:
    - nexus_data:/nexus-data
    
  fitnesse:
    image: jgerges/fitnesse
    container_name: fitnesse
    ports:
    - 9090:9090
    volumes:
    - fitnesse_data:/opt/fitnesse

  sonardb:
    image: postgres
    container_name: sonar_postgres
    ports:
    - 5432:5432
    environment:
    - DB_NAME=sonar
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    volumes:
    - postgresql:/var/lib/postgresql
    - postgresql_data:/var/lib/postgresql/data
    restart: always

volumes:
  sonarqube_extensions:
    external: true
  postgresql:
    external: true
  postgresql_data:
    external: true
  jenkins_data:
    external: true
  fitnesse_data:
    external: true
  nexus_data:
    external: true
  sonarqube_data:
    external: true
  sonarqube_extensions:
    external: true
  sonarqube_logs:
    external: true
  sonarqube_conf:
    external: true

networks:
  default:
    external:
      name: myNetwork                
