- hosts: 127.0.0.1
  connection: local

  tasks:  
  - name: tearing down the services
    docker_compose:
      project_src: .
      state: absent
  
  - name: backing up the sonar extensions
    copy:
      src: /data/docker/volumes/sonarqube_extensions
      dest: /data/jgerges/backups/sonarqube_extensions_backup
      backup: yes
    delegate_to: 127.0.0.1

  - name: creating postgresql data dump
    shell: docker exec sonar_postgres pg_dump -U sonar sonar > sonar.sql

  - name: copying sonar.sql dump file to a backup folder
    copy:
      src: /data/docker/volumes/postgresql_data/_data/sonar.sql
      dest: /data/jgerges/backups

  - name: clearing the extensions volume 
    file:
      path: /data/docker/volumes/sonarqube_extensions/_data/*
      state: absent
  
  - name: granting permissions for volumes
    file:
      path: /data/docker/volumes/
      state: directory
      mode: '777'
      recurse: yes
  
  - name: waking the services up
    environment:
      SONAR_IMAGE: sonarqube:$SONAR_VERSION
    docker_compose:
      project_src: .
  
  - name: waiting for sonarqube service to become available
    uri:
      url: http://localhost:9000/sonar/setup
      status_code: 200
    register: result
    until: result.status == 200
    retries: 30
    delay: 5

  - name: upgrading database
    uri:
      url: http://jgerges/sonar/api/system/migrate_db
      method: POST
